
openapi: 3.0.0
info:
  title: Overview Data
  version: '1.0'
components:
  schemas:
    AWS:
      type: object
      properties:
        name:
          type: string
          enum:
            - AWS
        value:
           example: 38
           pattern: "^[1-9][1-9]$"
    GoogleCloud:
      type: object
      properties:
        name:
          type: string
          enum:
            - GoogleCloud
        value:
           example: 38
           pattern: "^[1-9][1-9]$"
    Alibaba:
      type: object
      properties:
        name:
          type: string
          enum:
            - Alibaba
        value:
           example: 38
           pattern: "^[1-9][1-9]$"
    Azure:
      type: object
      properties:
        name:
          example: "As45da"
          pattern: "^[A-Z][a-z][1-9][1-9][a-z][a-z]$"   
        value:
           example: 38
           pattern: "^[1-9][1-9]$"        
    Cloud:
      type: object
      properties:
        cloudNetwork:
          type: array
          items:
            - $ref: '#/components/schemas/AWS'
            - $ref: '#/components/schemas/GoogleCloud'
            - $ref: '#/components/schemas/Alibaba'
            - $ref: '#/components/schemas/Azure'
        total:
          type: integer
          minimum: 1
          maximum: 1000
servers:
  - url: 'http://localhost:3000'
paths:
  /advance1:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cloud'
